# Generated by Django 5.1.1 on 2025-01-20 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distributors', '0002_paint'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pin',
            old_name='is_claimed',
            new_name='is_used',
        ),
        migrations.RemoveField(
            model_name='pin',
            name='claimed_at',
        ),
        migrations.RemoveField(
            model_name='pin',
            name='claimed_by',
        ),
        migrations.RemoveField(
            model_name='pin',
            name='coin_value',
        ),
        migrations.RemoveField(
            model_name='pin',
            name='pin_code',
        ),
        migrations.AddField(
            model_name='pin',
            name='code',
            field=models.CharField(default='default_code', max_length=100, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pin',
            name='coins',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
