# Generated by Django 5.1.1 on 2025-01-21 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distributors', '0003_rename_is_claimed_pin_is_used_remove_pin_claimed_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paintbucket',
            name='code',
            field=models.CharField(max_length=20),
        ),
    ]
